[config]
scheme_type = "scheme-monochrome"

[config.wallpaper]
set = false

[templates.ashen_colors]
input_path = "~/.config/matugen/templates/Colors.qml.template"
output_path = "/home/adolf-arch/ashen/quickshell/.config/quickshell/ashen/services/Colors.qml"
post_hook = "pkill -9 quickshell; sleep 0.3; quickshell -c ashen &"
