format = """
$directory$git_branch$git_status$cmd_duration
❯ """

[directory]
style = "bold #6272a4"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
style = "bold #a89bc8"

[git_status]
style = "bold #8a5a5a"

[cmd_duration]
min_time = 2_000
style = "bold #8a7a5a"
format = "took [$duration]($style) "

[character]
success_symbol = "[❯](bold #6272a4)"
error_symbol = "[❯](bold #8a5a5a)"
