# ══════════════════════════════════════════
#   Ashen — Hypridle
# ══════════════════════════════════════════
general {
    lock_cmd = qs ipc -c ashen call lockscreen lock
    before_sleep_cmd = qs ipc -c ashen call lockscreen lock
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Auto-bloqueo a los 5 minutos de inactividad
listener {
    timeout = 300
    on-timeout = qs ipc -c ashen call lockscreen lock
}

# Apagar pantalla a los 10 minutos (si sigue inactivo tras bloquear)
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
