# ══════════════════════════════════════════
#   Ashen — Kitty
# ══════════════════════════════════════════

# Font
font_family      JetBrainsMono NF
bold_font        JetBrainsMono NF Bold
italic_font      JetBrainsMono NF Italic
bold_italic_font JetBrainsMono NF Bold Italic
font_size        11.0

# Transparencia (el blur lo maneja Hyprland)
background_opacity 0.0

# Cursor
cursor_shape beam
cursor_beam_thickness 1.5

# Window
window_padding_width 12
hide_window_decorations yes

# Bell
enable_audio_bell no

# Tab bar
tab_bar_style powerline
tab_powerline_style slanted

# Colors — Ashen Ghost
foreground            #d4d4e0
background            #0f0f12
selection_foreground  #0f0f12
selection_background  #6272a4

color0  #080809
color1  #8a5a5a
color2  #5a7a6a
color3  #8a7a5a
color4  #6272a4
color5  #a89bc8
color6  #5a7a8a
color7  #d4d4e0
color8  #404052
color9  #c47a7a
color10 #7a9e7e
color11 #c4a882
color12 #8899cc
color13 #c8b8e8
color14 #7aaabb
color15 #e8e8f0

symbol_map U+E000-U+F8FF Material Symbols Rounded
